version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hidrosafe-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hidrosafe
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: hidrosafe-app
    depends_on:
      - db
    environment:
      DB_USERNAME: admin
      DB_PASSWORD: admin
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hidrosafe
    ports:
      - "8080:8080"
    restart: on-failure

    command: >
      sh -c "until pg_isready -h db -p 5432 -U postgres; do sleep 1; done; java -jar app.jar"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
